server:
  port: 8082

spring:
  application:
    name: config
  cloud:
     config:
      server:
        git:
          #Github上的git仓库名字
          uri: https://github.com/guolaizuozuo/springcloud-config.git
          ##搜索目录.这个目录指的是github上的目录
          search-paths:
            - springcloud-config
          username: guolaizuozuo
          password: Admin123~
        #读取分支
      label: master

  rabbitmq:
    host: 192.168.149.160
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

#rabbitmq相关设置 ，暴露 bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
