eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/
  #instance:
    #hostname: clientName
spring:
  application:
    name: client8081
server:
  port: 8081